Vagrant.configure(2) do |config|
	config.vm.box = "ubuntu/bionic64"
	config.vm.network "forwarded_port", guest: 80, host: 9080
	config.vm.network "forwarded_port", guest: 9000, host: 9001
	config.vm.provider "virtualbox" do |vb|
		vb.memory = "4048"
	end


	# Salt provisioning
	config.vm.provision "shell",
		path: "https://bootstrap.saltstack.com"

	config.vm.provision "shell",
		inline: "sudo salt-call --local state.highstate"

	config.vm.synced_folder "salt/", "/srv/salt/"

	# Uncomment these synced folders after Magento is installed to enable php deployment
	config.vm.synced_folder "../","/opt/MailPlus/MailPlus"

	config.vm.synced_folder "../", "/opt/mailplus"

	config.vm.synced_folder "share", "/srv/share"
end
