Vagrant.configure(2) do |config|
	config.vm.box = "ubuntu/trusty64"
	config.vm.network "forwarded_port", guest: 80, host: 8080
	config.vm.provider "virtualbox" do |vb|
		vb.memory = "2048"
	end
	#config.vm.provision "shell", inline: <<-SHELL
	# sudo apt-get update
	# sudo apt-get install -y apache2
	# sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password root'
	# sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password root'
	# sudo php5enmod mcrypt
	# mysql -u root -proot -e 'create database magento'
	# sudo cp /vagrant/Magento-CE-2.0.0+Samples-2015-11-17-06-29-31.tar.bz2 /var/www/html
	# cd /var/www/html && sudo tar -xjf Magento-CE-2.0.0+Samples-2015-11-17-06-29-31.tar.bz2
	# cd /var/www/html && chown www-data * -R
	# sudo service apache2 restart
	#SHELL


	# Salt provisioning
	config.vm.provision "shell",
		path: "https://bootstrap.saltstack.com"

	config.vm.provision "shell",
		inline: "sudo salt-call --local state.highstate"

	config.vm.synced_folder "salt/", "/etc/salt/"

end
