Vagrant.configure(2) do |config|
	config.vm.box = "bento/debian-11"
	config.vm.network "forwarded_port", guest: 80, host: 9080
	config.vm.network "forwarded_port", guest: 9000, host: 9201
	config.vm.provider "virtualbox" do |vb|
		vb.memory = "4048"
	end

	config.vm.synced_folder "salt/", "/srv/salt/"

	config.vm.provision :salt do |salt|
        salt.masterless = true
        salt.minion_config = "minion"
        salt.minion_id = "magento2.spotler.test"
        salt.run_highstate = true
        salt.install_type = "stable"
        salt.version = "3004"
        salt.bootstrap_options = "-x python3"
    end

    config.vm.define "plugin" do |plugin|
        plugin.vm.synced_folder "../", "/opt/MailPlus/MailPlus"
        plugin.vm.synced_folder "../", "/opt/mailplus"

        plugin.vm.provision "shell",
            inline: "salt-call --local state.sls plugin"
    end

end
