<?php 
  $websiteId = $this->getCurrentWebsite()->getId();
  $params['section'] = 'mailplus';
?>

<div>
	<h2>State for website <?php echo $this->escapeHtml($this->getCurrentWebsite()->getName());  ?></h2>

<?php if (!$this->isEnabledForSite($websiteId)) { ?>
	<p class="warning">The MailPlus Connector is disabled.</p>
<?php } else { ?>
	<p>The MailPlus Connector is enabled.</p>
<?php }?>


<?php if ($this->checkMailPlusApi($websiteId)) { ?>
	<p>Connection to MailPlus API is OK.</p>
<?php } else { ?>
	<p>Could not connect to the MailPlus API. Please check the 
		<?php echo '<a href="' . $block->getUrl('adminhtml/system_config/edit', $params) . '">the MailPlus Connector configuration</a>'; ?>	
	</p> 
<?php }?>	


</div>